apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperauth
  namespace: hyperauth
  labels:
    app: hyperauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperauth
  template:
    metadata:
      labels:
        app: hyperauth
    spec:
      volumes:
      - name: ssl
        secret:
          secretName: hyperauth-https-secret
      - name: kafka
        secret:
          secretName: hyperauth-kafka-jks
      - name: log
        persistentVolumeClaim:
          claimName: hyperauth-log-pvc          
      containers:
      - name: hyperauth
        image: tmaxcloudck/hyperauth:b1.0.16.17
#        args: ["-Dkeycloak.profile.feature.docker=enabled", "-b", "0.0.0.0"]                
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: HYPERAUTH_PASSWORD
        - name: CERTS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: CERTS_PASSWORD
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR     # postgres / tibero
          value: "postgres"     
        - name: DB_PORT       # postgres : 31226, tibero : 32571
          value: "31226"     
        - name: DB_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DB_USER
          value: "keycloak"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: DB_PASSWORD 
        - name: KEYCLOAK_WELCOME_THEME
          value: tmax
        - name: TZ
          value: Asia/Seoul  
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: ssl
          mountPath: /etc/x509/https
        - name: kafka
          mountPath: /etc/x509/kafka  
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
      - name: log-collector
        image: tmaxcloudck/hyperauth-log-collector:b0.0.0.6
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Seoul
          name: NAMESPACE
          value: hyperauth
        volumeMounts:
        - name: log
          mountPath: /go/src/logs
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"            
