apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hyperauth
  namespace: hyperauth
  labels:
    app: hyperauth
    release: prometheus
spec:
  selector:
    matchLabels:
      app: keycloak
  endpoints:
  - path: /auth/realms/tmax/metrics
    port: http
    interval: 15s
    basicAuth:
      password:
        name: passwords
        key: HYPERAUTH_PASSWORD
      username:
        name: passwords
        key: HYPERAUTH_ADMIN
