apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kafka-client-jks-certificate
  namespace: hyperauth
spec:
  secretName: kafka-client-jks
  commonName: kafka-client
  isCA: false
  keySize: 2048
  duration: 8760h # 360d=1y
  renewBefore: 720h # 30d
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  keystores:
    jks:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: CERTS_PASSWORD
        name: passwords
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: tmaxcloud-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: hyperauth
spec:
  containers:
  - name: kafka-client
    image: quay.io/strimzi/kafka:0.25.0-kafka-2.8.0
    command: ["/bin/bash"]
    args: [ "-c", 'for((i=0;;i+=1)); do echo "Up time: \$i min" && sleep 60; done' ]
    volumeMounts:
    - name: truststore
      mountPath: /opt/kafka/certificates
      readOnly: true
  volumes:
  - name: truststore
    secret:
      secretName: kafka-client-jks
