## ref https://cert-manager.io/next-docs/reference/api-docs/#cert-manager.io%2fv1alpha3
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-bu: tmax-cloud
    app.kubernetes.io/name: api-gateway
  name: tmaxcloud-selfsigned
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-bu: tmax-cloud
    app.kubernetes.io/name: api-gateway
  name: tmaxcloud-ca
  namespace: cert-manager
spec:
  secretName: tmaxcloud-ca
  duration: 8760h # 360d=1y
  renewBefore: 720h # 30d
  commonName: tmaxcloud
  isCA: true
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-selfsigned

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-bu: tmax-cloud
    app.kubernetes.io/name: api-gateway
  name: tmaxcloud-issuer
spec:
  ca:
    secretName: tmaxcloud-ca
